// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/barChart.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/lineChart.tsx";
import * as $5 from "./routes/pieChart.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Graph.tsx";
import * as $$2 from "./islands/Histogram.tsx";
import * as $$3 from "./islands/Home.tsx";
import * as $$4 from "./islands/PieChart.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/barChart.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/lineChart.tsx": $4,
    "./routes/pieChart.tsx": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Graph.tsx": $$1,
    "./islands/Histogram.tsx": $$2,
    "./islands/Home.tsx": $$3,
    "./islands/PieChart.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
